CREATE SCHEMA IF NOT EXISTS coffee_ledger;

CREATE TABLE IF NOT EXISTS coffee_ledger.people (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    display_order integer NOT NULL,
    deactivated_at timestamptz,
    CONSTRAINT people_name_len CHECK (char_length(name) >= 1),
    CONSTRAINT people_display_order_pos CHECK (display_order >= 1),
    CONSTRAINT people_name_key UNIQUE (name),
    CONSTRAINT people_display_order_key UNIQUE (display_order)
);

CREATE INDEX IF NOT EXISTS people_active_order_idx
    ON coffee_ledger.people (display_order)
    WHERE deactivated_at IS NULL;

CREATE TABLE IF NOT EXISTS coffee_ledger.cup_price (
    id integer PRIMARY KEY,
    amount integer NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT cup_price_id_one CHECK (id = 1),
    CONSTRAINT cup_price_amount_pos CHECK (amount >= 1)
);

CREATE TABLE IF NOT EXISTS coffee_ledger.drinks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id integer NOT NULL,
    unit_price integer NOT NULL,
    recorded_at timestamptz NOT NULL,
    cancelled_at timestamptz,
    CONSTRAINT drinks_unit_price_pos CHECK (unit_price >= 1),
    CONSTRAINT drinks_person_fk
        FOREIGN KEY (person_id) REFERENCES coffee_ledger.people (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS drinks_person_recorded_idx
    ON coffee_ledger.drinks (person_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS drinks_person_active_idx
    ON coffee_ledger.drinks (person_id)
    WHERE cancelled_at IS NULL;

CREATE INDEX IF NOT EXISTS drinks_cancelled_idx
    ON coffee_ledger.drinks (cancelled_at)
    WHERE cancelled_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS coffee_ledger.payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id integer NOT NULL,
    amount integer NOT NULL,
    recorded_at timestamptz NOT NULL,
    cancelled_at timestamptz,
    CONSTRAINT payments_amount_pos CHECK (amount >= 1),
    CONSTRAINT payments_person_fk
        FOREIGN KEY (person_id) REFERENCES coffee_ledger.people (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS payments_person_recorded_idx
    ON coffee_ledger.payments (person_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS payments_recorded_active_idx
    ON coffee_ledger.payments (recorded_at)
    WHERE cancelled_at IS NULL;

CREATE INDEX IF NOT EXISTS payments_person_active_idx
    ON coffee_ledger.payments (person_id)
    WHERE cancelled_at IS NULL;

CREATE INDEX IF NOT EXISTS payments_cancelled_idx
    ON coffee_ledger.payments (cancelled_at)
    WHERE cancelled_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS coffee_ledger.safe_deposits (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount integer NOT NULL,
    deposited_at timestamptz NOT NULL,
    CONSTRAINT safe_deposits_amount_pos CHECK (amount >= 1)
);

CREATE INDEX IF NOT EXISTS safe_deposits_deposited_idx
    ON coffee_ledger.safe_deposits (deposited_at DESC);

CREATE TABLE IF NOT EXISTS coffee_ledger.operation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at timestamptz NOT NULL,
    operation_type varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    CONSTRAINT operation_logs_type_check CHECK (operation_type IN (
        'person_registered',
        'person_deactivated',
        'display_order_changed',
        'cup_price_registered',
        'cup_price_updated',
        'drink_recorded',
        'drink_cancelled',
        'payment_recorded',
        'payment_cancelled',
        'safe_deposited',
        'vault_operated',
        'unpaid_adjusted'
    ))
);

CREATE INDEX IF NOT EXISTS operation_logs_occurred_idx
    ON coffee_ledger.operation_logs (occurred_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS coffee_ledger.vault_operations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason varchar(200) NOT NULL,
    direction varchar(16) NOT NULL,
    amount integer NOT NULL,
    reason_date date NOT NULL,
    entered_at timestamptz NOT NULL,
    CONSTRAINT vault_operations_reason_len CHECK (char_length(reason) >= 1),
    CONSTRAINT vault_operations_direction_check CHECK (direction IN ('deposit', 'withdrawal')),
    CONSTRAINT vault_operations_amount_pos CHECK (amount >= 1)
);

CREATE INDEX IF NOT EXISTS vault_operations_entered_idx
    ON coffee_ledger.vault_operations (entered_at DESC, id DESC);
