CREATE TABLE IF NOT EXISTS coffee_ledger.vault_operations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason varchar(200) NOT NULL,
    direction varchar(16) NOT NULL,
    amount integer NOT NULL,
    reason_date date NOT NULL,
    entered_at timestamptz NOT NULL,
    CONSTRAINT vault_operations_reason_len CHECK (char_length(reason) >= 1),
    CONSTRAINT vault_operations_direction_check CHECK (direction IN ('deposit', 'withdrawal')),
    CONSTRAINT vault_operations_amount_pos CHECK (amount >= 1)
);

CREATE INDEX IF NOT EXISTS vault_operations_entered_idx
    ON coffee_ledger.vault_operations (entered_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS drinks_cancelled_idx
    ON coffee_ledger.drinks (cancelled_at)
    WHERE cancelled_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS payments_cancelled_idx
    ON coffee_ledger.payments (cancelled_at)
    WHERE cancelled_at IS NOT NULL;

ALTER TABLE coffee_ledger.operation_logs
    DROP CONSTRAINT IF EXISTS operation_logs_type_check;

ALTER TABLE coffee_ledger.operation_logs
    ADD CONSTRAINT operation_logs_type_check CHECK (operation_type IN (
        'person_registered',
        'person_deactivated',
        'display_order_changed',
        'cup_price_registered',
        'cup_price_updated',
        'drink_recorded',
        'drink_cancelled',
        'payment_recorded',
        'payment_cancelled',
        'safe_deposited',
        'vault_operated',
        'unpaid_adjusted'
    ));
