CREATE TABLE IF NOT EXISTS coffee_ledger.unpaid_adjustments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id integer NOT NULL,
    previous_amount integer NOT NULL,
    new_amount integer NOT NULL,
    reason varchar(200) NOT NULL,
    occurred_at timestamptz NOT NULL,
    CONSTRAINT unpaid_adjustments_person_fk
        FOREIGN KEY (person_id) REFERENCES coffee_ledger.people (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT unpaid_adjustments_previous_nonneg CHECK (previous_amount >= 0),
    CONSTRAINT unpaid_adjustments_new_nonneg CHECK (new_amount >= 0),
    CONSTRAINT unpaid_adjustments_amount_changed CHECK (new_amount <> previous_amount),
    CONSTRAINT unpaid_adjustments_reason_len CHECK (char_length(reason) >= 1)
);

CREATE INDEX IF NOT EXISTS unpaid_adjustments_person_idx
    ON coffee_ledger.unpaid_adjustments (person_id);

CREATE INDEX IF NOT EXISTS unpaid_adjustments_occurred_idx
    ON coffee_ledger.unpaid_adjustments (occurred_at DESC, id DESC);

ALTER TABLE coffee_ledger.operation_logs
    DROP CONSTRAINT IF EXISTS operation_logs_type_check;

ALTER TABLE coffee_ledger.operation_logs
    ADD CONSTRAINT operation_logs_type_check CHECK (operation_type IN (
        'person_registered',
        'person_deactivated',
        'display_order_changed',
        'cup_price_registered',
        'cup_price_updated',
        'drink_recorded',
        'drink_cancelled',
        'payment_recorded',
        'payment_cancelled',
        'safe_deposited',
        'vault_operated',
        'unpaid_adjusted'
    ));
